### ISSUE TITLE
What could be the meaning behind the error undefined reference to 'yylex()'

### ISSUE THREAD

**Issue by MK2020** [LangProc/langproc-2017-lab#13]
I tried looking this up some sources suggested that it could be due to inconsistencies between C and C++ . What do you think is causing this error if its possible to tell?

Thanks

**Comment by zs3815** [comment]
I had that problem too when I changed the IDE to fully C++11 but haven't fixed it yet

**Comment by m8pple** [comment]
My guess is that it is because you are compiling
histogram_main.cpp, but not then linking in
histogram_lexer.yy.cpp [1].

The program has two key functions:

- main : defined in histogram_main.cpp

- yylex : defined in histogram_lexer.yy.cpp


If your IDE does the equivalent of:

     g++ -o histogram_main histogram_main.cpp

which is what most IDEs do by default, then the
linker can find the function main, but can't find
the function yylex as it hasn't been told about
the source file.

You need your IDE to do the equivalent of:

     g++ -o histogram histogram_main.cpp histogram_lexer.yy.cpp

You also ideally need your IDE to apply the same
C++ settings when compiling both files, so they
should both have C++11 enabled if your IDE doesn't
enable it by default.

How you do this depends on the IDE. For eclipse, the
following might help, esp. step 2:
http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Fgetting_started%2Fcdt_w_import.htm

If you're _not_ in an IDE and are using the makefile, then
I wouldn't expect to see any errors.

Can you include a log or screenshot showing what your are
trying to build, then where the error occurs?

David Thomas

[1] - Or whatever the output of flex is called, I can't see
       the repo right now.
