### ISSUE TITLE
Part a quotation words spanning new lines

### ISSUE THREAD

**Issue by fpgamy** [LangProc/langproc-2017-lab#15]
The readme of part A states: 

"Any sequence of characters beginning with " starts a word, and the word ends at the next ". The word itself does not include the surrounding " characters. _It is illegal for such a sequence to span a new-line._"

However, the ref file for test 27 has 
`"struct
\n * page" 1`
which spans 2 lines. Could we have a clarification as to whether the new line should cause the sequence to count as one word or two words?

**Comment by m8pple** [comment]
The input is illegal - so test 27 is not valid input
given the spec.

So that's an error on my part in at least three ways:

- in terms of input, I didn't check for lonely
   quotes properly. I remember running a regex
   over it to look for lonely quotes, but probably
   the regex wasn't correct, and I accepted the
   absence of evidence as evidence of absence due
   to confirmation bias.

- my reference doesn't actually contain any
   error handling, and assumes the input will
   actually follow the spec.

- There is an implicit spec for the output format
   grammar, so I should have checked the reference
   output at least matched that.

Thanks for spotting that, I'll update the reference.

It's kind of amusing that it is exactly one line
that does it.

David Thomas

**Comment by divyanshmanocha** [comment]
Apologies, the regex now still has two alternatives: is "something \n (without an end quote) considered as a string literal or invalid?
Could you please confirm which of the two it is?
