### ISSUE TITLE
Capture groups in lexers?

### ISSUE THREAD

**Issue by Carotti** [LangProc/langproc-2017-lab#16]
Apparently, [flex does not support capture groups](http://stackoverflow.com/questions/6051196/get-groups-with-flex). Wouldn't this be a particularly useful feature? 

e.g. rather than having to write a C function to remove quotes from words which are surrounded by quotes, you could put a capture group inside the quotes of the regex (I'm deliberately not posting an example!). Then you could do something like `yytext.captureGroup(1)`.

Are there any lexers that support this?

**Comment by m8pple** [comment]
I don't remember ever seeing a lexer/scanner tool that supports it, as there
is always the argument that you can just do the extraction in the action.

From an implementation point of view it would also be tricky, as flex is taking
all your regular expressions for each token, then merging them into one
giant FSA with an accepting state for each token. It runs the FSA until it can't
consume any more characters, then the accepting state tells it which rule it
should be. If you had capture groups, it would need to maintain the capture
group information for each token as it runs - not impossible, as you have to do
that in a normal regex engine, e.g.:
````
$ sed -E -e "s/a(.)b|c(.)d/\1,\2/g"
axb
x,
cyd
,y
````
So you could take the capture groups from the global giant regular expression, then
remap them to the groups within the local per-token regular expression.

My guess is that it is down to simplicity and speed. The lexer has to run a potentially
very large FSA, and you want that to be as small and fast as possible. Anything
which makes the per-character cost higher is a bad idea. They could construct
the global regex without groups, then automatically run the local regex again
once it matches to get the local groups, but then... so could you.


One place where you do get this functionality is in embedded lexer/parser
frameworks. For example, I sometimes use [Boost.Spirit](http://boost-spirit.com/home/),
which is an EDSL in C++ for building parsers. There you can get capture
groups within a token, but mainly because it doesn't really distinguish
between lexing and parsing, nor does it rely on a separate tool to generate
those things.

**Comment by Carotti** [comment]
Interesting! That definitely explains why they don't implement capture groups. Letting the person using the lexer generate function-specific code for implementing what they want to do is going to be a lot faster. 

I'll take a look at Boost.Spirit anyway. 

Thanks for your response!
