### ISSUE TITLE
Shell script for testing optimisation (Codegen)

### ISSUE THREAD

**Issue by martinferianc** [LangProc/langproc-2017-lab#37]
I think I have found a few problems in the shell script for testing the intermediate part for Codegen. When I was trying to run the script on Vagrant I immediately got this error: 

```
./test_simplifier.sh: line 6: syntax error near unexpected token `then'
./test_simplifier.sh: line 6: `while [[ "$CHANGED" -ne 0 ]]; then'
```

Changing it to: 
```
while [[ "$CHANGED" -ne 0 ]] ; do
```

and the end instead of `fi` `done`

Then I believe that the spec says that 

> Each program should read its input from stdin, and write the transformed tree to stdout. They should produce a return-value of 0 (success) if they managed to simplify the tree, or 1 (failure) if they are returning the tree unchanged. Either way, the tree should still be written back out to stdout.

But the shell script is not testing for equaling to 0 but to 1 which indicates that the tree remained unchanged, resulting in an infinite loop.

Changing all the conditions: 
```
if [[ "$?" -eq "0" ]]; then
    CHANGED=1;
 fi
```

solved the problem.

**Comment by m8pple** [comment]
Ah - this was one of those situations where when I say "something like",
it is a complete sketch that is typed in free-hand, rather than something
I expect to work verbatim (particularly for the later parts). 

But I probably should have made it pseudo-code for that to be clear,
so there probably is an implicit expectation that the code works verbatim.
If I were to re-write from scratch, I'd probably make it pseudo-code

Thanks, I'll adjust as you suggest.

**Comment by lorenzo2897** [comment]
@m8pple You missed out the `fi` on line 513 of the codegen readme, which should be `done` to match the opening `do`
