### ISSUE TITLE
Passing 1/10 Tests

### ISSUE THREAD

**Issue by luisi-at** [LangProc/langproc-2017-lab#43]
On the initial run, without edits to the interpreter, the test script tells me that there is 1 test passing. It appears to be test 5. Am I right in thinking this is undefined behavior?

**Comment by m8pple** [comment]
It is just because the skeleton implementation happens to handle
numbers, and the only thing that test 5 looks at is whether the
interpreter/compiler can deal with numbers.

So basically, everybody get's one for free. Unless... their compiler
or interpreter doesn't compile or crashes.

-
While the test script is being used for assessment, my original
goal in writing them is as tests of correctness (because the goal is
to write correct programs).

The general process I use for these labs is:

1 - Write the spec, including the readme and the test inputs (and some test outputs)
2 - Setup the testing infrastructure (though probably with some bugs, as there is no
    implementation yet).
2 - Implement the spec in a different reference repository, to check it can be done, see
     how difficult it is; adjust if necessary. Fix-up the testing infrastructure if nesc.
3 - Copy parts of the reference back into the spec, including the full reference outputs.
4 - "degrade" the reference input implementation so that most of it is still to be done,
    but there is just enough left to give a starting point.

Arguably I should have re-written the test script or inputs so that it returns
zero by default, but then we're left with either:
- There can't be a standalone test for "do numbers work", which
   is bad testing practise.
- The skeleton should contain no code for supporting numbers,
  in which case it is difficult to have it do anything out of the box.

**Comment by luisi-at** [comment]
I wondered if that was indeed the case. It was also that the output of the test was this:

![screen shot 2017-02-18 at 15 40 09](https://cloud.githubusercontent.com/assets/17338500/23094428/9294f6b8-f5f0-11e6-9411-c80978af06ef.png)

Clearly there should be an output there (5 as is in the input program) but this isn't being shown on the console. Having been focussing on the code part, I haven't yet had a proper chance to delve into the test script hence my curiosity as to why this test was passing. 

Turns out that there are no parameters passed into the test anyway and the console output is just a template...
