### ISSUE TITLE
Long labels

### ISSUE THREAD

**Issue by louiskueh** [LangProc/langproc-2017-lab#47]
During *part 2 : code gen* I noticed that if my labels were too long the vm would truncate the number for the label 

i.e. `_thislabelistoolong_39 -> _thislabelistoolong_3`

causing failure for test 10

**Comment by m8pple** [comment]
Yes, the VM assembler has some implementation defined limits, mainly due to the
way it "parses" the assembly:
https://github.com/LangProc/langproc-2016-lab/blob/master/3-codegen/src/vm.cpp#L328
and
https://github.com/LangProc/langproc-2016-lab/blob/master/3-codegen/src/vm.cpp#L336

Maybe 16 was a bit low, given you are generating labels. However, it's good that the
testing regime is catching it.

I'll lift it to 64 (which is _sure_ to be enough :), and document the limit.
