### ISSUE TITLE
Typo and confusion about freeing pointer to wordValue

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2017-lab#5]
_Firstly_, in this comment:
```          
// We have a string. The value is in a string
// _pointed to_ by yylval.stringValue. Note that
// the string is allocated by the lexer, but
// deallocated by us.
```
Do you mean yylval.wordValue?
`// Free the pointer yylval.wordValue to stop leaks`

_Secondly_, yylval and yylval.wordValue aren't initialised with `new`, so when I do `delete yylval.wordvalue` or `delete yylval` I get a segmentation fault. How are we supposed to free them?

**Comment by ps-george** [comment]
Figured out the second one; `yylval.wordValue` does need to be initialised with `new`.

**Comment by m8pple** [comment]
On the first - yes, it's a type. Fixed, thanks.

On the second: your actions establish a protocol between the lexer action
which produces the value, and the histogram which consumes the value.
So you are on both sides - you'll free in the histogram, but only because you
new'd in the lexer.

So if you are not using new on the lexer side then it will segfault if you
delete it, but then presumably it also segfaults when you do the comment
before the delete:

    // TODO: add yylval.wordValue to histogram

**Comment by ps-george** [comment]
Thanks
