### ISSUE TITLE
Issue with tests 25, 26 and 27

### ISSUE THREAD

**Issue by lorenzo2897** [LangProc/langproc-2017-lab#6]
Tests 25 to 27 incorrectly fail on a correct lexer.

**Comment by martinferianc** [comment]
I have the same problem especially, with capital letters.

**Comment by dan12n** [comment]
It seems that capital letters are not included in the lexer from which reference files have been generated. Also I am not sure about this in stdout.ref:
```
 "struct
 * page" 1
```

Should struct not be recognised as a word by itself, since it is on a separate line?

**Comment by divyanshmanocha** [comment]
It seems that capital letters are not included in the lexer that generated the reference outputs. Could you please confirm if this is on purpose?

**Comment by luisi-at** [comment]
The default test output appears to be ignoring or removing capital letters of reference text words that start with a capital as stated above. The issue however does not affect all lower case words and upon closer inspection to the reference output for test 27, all of the words appear to be lower case anyway. As above, is it the reference that is wrong or the specification?

**Comment by m8pple** [comment]
It's the reference that is wrong, for a similar reason to #8.

It's nice to see consensus building that either the reference is wrong or the specification is wrong,
plus some suggestions of fixes.

The general principle that I (and most people) will adhere to is that the specification
is always right, unless:
1 - it turns out the specification turns out to be impossible or incoherent once you 
     sit down and try to build it (this happens a lot for real specs under the [waterfall model](https://en.wikipedia.org/wiki/Waterfall_model))
2 - implementation reveals that the specification is prohibitively expensive, or
     precludes big optimisations/simplifications that turn up when doing the coding
3 - the spec is still private, and so can be locally mutated without global inconsistencies

The lab specs are all published, and optimisation doesn't matter much here, so
unless 1 applies, the specification should always be seen as the master, and
the reference is wrong.

An example of 1 applying is in #7, where the spec was incorrect, but the reference
was right.
